teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4
#button mapping for ps3 controller connected via usb
    #enable_button: 6  # L2 shoulder button
    enable_turbo_button: 4  # L1 shoulder button
    require_enable_button: false
