# Request

# The robot will explore the environment for `explore_duration` time.
# After that, it will try to dock as soon as it sees the docking station.
# The `max_runtime` duration defines when the behavior should end regardless of whether
# the dock has been found or not. 

builtin_interfaces/Duration explore_duration
builtin_interfaces/Duration max_runtime
---
# Result
bool success
bool is_docked
builtin_interfaces/Duration duration
---
# Feedback

int32 DOCK = 0
int32 DRIVE_STRAIGHT = 1
int32 ROTATE = 2
int32 SPIRAL = 3
int32 UNDOCK = 4

int32 current_behavior
